export const QUESTIONS = [
  // 固定8問
  { id:"FIX_FI_01", axis:"FI", side:"F", text:"会話中に『これ構造的に面白いな』と思うことがある。", category:"core", weight:1.3, fixed:true },
  { id:"FIX_FI_02", axis:"FI", side:"F", text:"69という数字を見ると、意味を考えてしまうことがある。", category:"neta", weight:1.0, fixed:true },
  { id:"FIX_RC_01", axis:"RC", side:"C", text:"グループでは主導権を握る側になることが多い。", category:"core", weight:1.3, fixed:true },
  { id:"FIX_RC_02", axis:"RC", side:"C", text:"人から『ドSっぽい』と言われたことがある。", category:"neta", weight:1.1, fixed:true },
  { id:"FIX_OA_01", axis:"OA", side:"O", text:"人の反応を見るのが楽しいと感じることがある。", category:"core", weight:1.2, fixed:true },
  { id:"FIX_OA_02", axis:"OA", side:"A", text:"気になることがあると、自分から試してみることがある。", category:"core", weight:1.2, fixed:true },
  { id:"FIX_TP_01", axis:"TP", side:"T", text:"少し恥ずかしい状況でも意外と平気なことがある。", category:"neta", weight:1.3, fixed:true },
  { id:"FIX_TP_02", axis:"TP", side:"T", text:"ゲームなどで縛りプレイや高難易度に挑戦したくなることがある。", category:"core", weight:1.3, fixed:true },

  // =========================
  // FI 40問
  // =========================
  { id:"FI_01", axis:"FI", side:"F", text:"トラブルが起きたとき、すぐ対応するより先に『なぜ起きたのか』を考えることが多い。", category:"core", weight:1.5, fixed:false },
  { id:"FI_02", axis:"FI", side:"I", text:"映画やドラマを見ると、演出や構造より登場人物の気持ちに共感することが多い。", category:"core", weight:1.5, fixed:false },
  { id:"FI_03", axis:"FI", side:"F", text:"議論を見るとき、どちらが好きかより『なぜ意見が分かれているのか』を考えることが多い。", category:"core", weight:1.5, fixed:false },
  { id:"FI_04", axis:"FI", side:"I", text:"物語を見るとき、設定の巧さより『自分ならどう感じるか』を大事にする。", category:"core", weight:1.5, fixed:false },
  { id:"FI_05", axis:"FI", side:"F", text:"人間関係の揉め事を見ると、感情より構造に注目してしまうことがある。", category:"core", weight:1.5, fixed:false },
  { id:"FI_06", axis:"FI", side:"I", text:"会話の流れより、その場で自分が何を感じるかを大事にすることが多い。", category:"core", weight:1.5, fixed:false },
  { id:"FI_07", axis:"FI", side:"F", text:"出来事を『パターン』として捉える癖がある。", category:"core", weight:1.5, fixed:false },
  { id:"FI_08", axis:"FI", side:"I", text:"物事を考えるとき、客観視より当事者の感覚に入り込みやすい。", category:"core", weight:1.5, fixed:false },

  { id:"FI_09", axis:"FI", side:"F", text:"自分の感情を、一歩引いて観察しているように感じることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_10", axis:"FI", side:"I", text:"感情が動いたとき、そのまま流れに乗ることが多い。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_11", axis:"FI", side:"F", text:"会話の内容より、言い回しや構図のほうが気になることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_12", axis:"FI", side:"I", text:"作品では設定より『感情が刺さるか』を重視する。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_13", axis:"FI", side:"F", text:"ニュースを見るとき、善悪より背景や仕組みが気になる。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_14", axis:"FI", side:"I", text:"他人の話を聞くとき、まず感情移入してしまう。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_15", axis:"FI", side:"F", text:"相手の本音や立場を構造的に考えることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_16", axis:"FI", side:"I", text:"物語や出来事の中に自分を重ねて考えることが多い。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_17", axis:"FI", side:"F", text:"感情が大きく動くと、逆に客観的になってしまうことがある。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_18", axis:"FI", side:"I", text:"その場の空気に飲まれて、自分の考え方が変わることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_19", axis:"FI", side:"F", text:"状況を『俯瞰して見る』ことが得意だと思う。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_20", axis:"FI", side:"I", text:"物事にはまず『入り込んでみる』方だ。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_21", axis:"FI", side:"F", text:"自分の行動について、後から分析して理由を考えることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_22", axis:"FI", side:"I", text:"考える前に気持ちが先に動くことがある。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_23", axis:"FI", side:"F", text:"出来事を、個人の感情より大きな流れとして見ることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_24", axis:"FI", side:"I", text:"その場でどう感じたかが、自分にとって一番大切だ。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_25", axis:"FI", side:"F", text:"人間関係を見ていて、役割分担や力関係が気になることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_26", axis:"FI", side:"I", text:"人間関係を見ていて、その人の気持ちの方が先に気になる。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_27", axis:"FI", side:"F", text:"客観的に見るクセが強い方だと思う。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_28", axis:"FI", side:"I", text:"自分がその場にいるつもりで考えることが多い。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_29", axis:"FI", side:"F", text:"人の発言の裏にある意図を読み取ろうとすることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_30", axis:"FI", side:"I", text:"人の発言をまず感情として受け取ることが多い。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_31", axis:"FI", side:"F", text:"『自分は今こう感じているな』と実況のように考えることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_32", axis:"FI", side:"I", text:"出来事の中に入ると、周りが見えなくなるくらい没入することがある。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_33", axis:"FI", side:"F", text:"感動した場面でも、どこかで構成や意図を考えてしまう。", category:"normal", weight:1.0, fixed:false },
  { id:"FI_34", axis:"FI", side:"I", text:"自分が入り込める物語や体験ほど強く記憶に残る。", category:"normal", weight:1.0, fixed:false },

  { id:"FI_35", axis:"FI", side:"F", text:"映画の名シーンを見ると、感動より構成のうまさに目がいくことがある。", category:"neta", weight:0.9, fixed:false },
  { id:"FI_36", axis:"FI", side:"I", text:"ドラマで修羅場になると、構造より気持ちの方に引っ張られる。", category:"neta", weight:0.9, fixed:false },
  { id:"FI_37", axis:"FI", side:"F", text:"SNSの炎上を見ると、怒る前に仕組みを分析したくなる。", category:"neta", weight:0.9, fixed:false },
  { id:"FI_38", axis:"FI", side:"I", text:"炎上を見ると、理屈より先に『つらそう』と思ってしまう。", category:"neta", weight:0.9, fixed:false },
  { id:"FI_39", axis:"FI", side:"F", text:"ケンカを見たとき、感情より先に原因を整理してしまう。", category:"neta", weight:0.9, fixed:false },
  { id:"FI_40", axis:"FI", side:"I", text:"誰かが泣いていると、理由より先に気持ちを受け取ってしまう。", category:"neta", weight:0.9, fixed:false },

  // =========================
  // RC 40問
  // =========================
  { id:"RC_01", axis:"RC", side:"R", text:"グループでは指示を出すより、状況に合わせて動くことが多い。", category:"core", weight:1.5, fixed:false },
  { id:"RC_02", axis:"RC", side:"C", text:"気付くと自分が場の流れを決めていることがある。", category:"core", weight:1.5, fixed:false },
  { id:"RC_03", axis:"RC", side:"R", text:"誰かが決めたルールの中で動く方が楽だと感じることがある。", category:"core", weight:1.5, fixed:false },
  { id:"RC_04", axis:"RC", side:"C", text:"物事は自分のやり方で進めたいと思うことが多い。", category:"core", weight:1.5, fixed:false },
  { id:"RC_05", axis:"RC", side:"R", text:"強い人についていく方が安心できることがある。", category:"core", weight:1.5, fixed:false },
  { id:"RC_06", axis:"RC", side:"C", text:"相手が迷っていると、自分が決めたくなることがある。", category:"core", weight:1.5, fixed:false },
  { id:"RC_07", axis:"RC", side:"R", text:"お願いされると断りにくい方だ。", category:"core", weight:1.5, fixed:false },
  { id:"RC_08", axis:"RC", side:"C", text:"誰かを導く立場の方が自然だと感じることがある。", category:"core", weight:1.5, fixed:false },

  { id:"RC_09", axis:"RC", side:"R", text:"強く言われると、つい従ってしまうことがある。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_10", axis:"RC", side:"C", text:"曖昧な空気になると、自分で締めたくなることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_11", axis:"RC", side:"R", text:"相手に任せる方がスムーズだと思うことがある。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_12", axis:"RC", side:"C", text:"自分が主導した方が早いと思うことがある。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_13", axis:"RC", side:"R", text:"相手の期待に合わせて立ち位置を変えることが多い。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_14", axis:"RC", side:"C", text:"自分の考えに周りを合わせたいと思うことがある。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_15", axis:"RC", side:"R", text:"会話では聞き役や受け役になることが多い。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_16", axis:"RC", side:"C", text:"会話では自然と仕切る側になることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_17", axis:"RC", side:"R", text:"誰かに頼られるより、頼る方が気楽なことがある。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_18", axis:"RC", side:"C", text:"頼られると張り切る方だ。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_19", axis:"RC", side:"R", text:"圧の強い人がいると、自分は一歩引くことが多い。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_20", axis:"RC", side:"C", text:"圧の弱い空気だと、自分が握りたくなることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_21", axis:"RC", side:"R", text:"対立が起きると、自分は受けに回りやすい。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_22", axis:"RC", side:"C", text:"対立が起きると、自分が主導を取りたくなる。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_23", axis:"RC", side:"R", text:"空気を壊さないために自分を下げることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_24", axis:"RC", side:"C", text:"場を壊さないために、あえて自分が締めることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_25", axis:"RC", side:"R", text:"相手の指示が明確だと動きやすい。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_26", axis:"RC", side:"C", text:"相手が迷っているとイライラしてしまうことがある。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_27", axis:"RC", side:"R", text:"言われた通りにやる方が得意だ。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_28", axis:"RC", side:"C", text:"自分で決めて動く方が得意だ。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_29", axis:"RC", side:"R", text:"相手の意見を受け止めてから動くことが多い。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_30", axis:"RC", side:"C", text:"相手に考えを飲ませることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_31", axis:"RC", side:"R", text:"指示されると『そういう役割なんだな』と納得しやすい。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_32", axis:"RC", side:"C", text:"主導権が宙に浮くと、自分で持ちたくなる。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_33", axis:"RC", side:"R", text:"人に合わせること自体に安心感を覚えることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"RC_34", axis:"RC", side:"C", text:"人を導く立場にいると、自分らしくいられることがある。", category:"normal", weight:1.0, fixed:false },

  { id:"RC_35", axis:"RC", side:"R", text:"人のペースに合わせることが苦ではない。", category:"neta", weight:0.9, fixed:false },
  { id:"RC_36", axis:"RC", side:"C", text:"指示を出す立場にいると、妙に落ち着くことがある。", category:"neta", weight:0.9, fixed:false },
  { id:"RC_37", axis:"RC", side:"R", text:"『流されやすい』と言われたことがある。", category:"neta", weight:0.9, fixed:false },
  { id:"RC_38", axis:"RC", side:"C", text:"『仕切りたがり』と言われたことがある。", category:"neta", weight:0.9, fixed:false },
  { id:"RC_39", axis:"RC", side:"R", text:"強い人に任せると安心することがある。", category:"neta", weight:0.9, fixed:false },
  { id:"RC_40", axis:"RC", side:"C", text:"『私が決める』と言いたくなる瞬間がある。", category:"neta", weight:0.9, fixed:false },

  // =========================
  // OA 40問
  // =========================
  { id:"OA_01", axis:"OA", side:"O", text:"人の行動を観察するのが好きなことがある。", category:"core", weight:1.5, fixed:false },
  { id:"OA_02", axis:"OA", side:"A", text:"気になることがあると、とりあえず自分で試してみる。", category:"core", weight:1.5, fixed:false },
  { id:"OA_03", axis:"OA", side:"O", text:"新しいことをする前に、まず様子を見ることが多い。", category:"core", weight:1.5, fixed:false },
  { id:"OA_04", axis:"OA", side:"A", text:"考えるより先に動くことがある。", category:"core", weight:1.5, fixed:false },
  { id:"OA_05", axis:"OA", side:"O", text:"場の空気を読んでから動くことが多い。", category:"core", weight:1.5, fixed:false },
  { id:"OA_06", axis:"OA", side:"A", text:"空気を変えたいと思うと、自分から何かすることがある。", category:"core", weight:1.5, fixed:false },
  { id:"OA_07", axis:"OA", side:"O", text:"人の表情や反応をよく見ている方だ。", category:"core", weight:1.5, fixed:false },
  { id:"OA_08", axis:"OA", side:"A", text:"会話や場の流れに、自分から介入することがある。", category:"core", weight:1.5, fixed:false },

  { id:"OA_09", axis:"OA", side:"O", text:"会話では話すより聞く側になりやすい。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_10", axis:"OA", side:"A", text:"会話では流れを動かす発言をしがちだ。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_11", axis:"OA", side:"O", text:"相手の出方を見てから決めたいことが多い。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_12", axis:"OA", side:"A", text:"まず自分がやってみて、その結果を見ることが多い。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_13", axis:"OA", side:"O", text:"変化を起こすより、変化を見届ける方が好きだ。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_14", axis:"OA", side:"A", text:"変化が欲しいとき、自分からきっかけを作る。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_15", axis:"OA", side:"O", text:"行動する前に相手の様子を探ることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_16", axis:"OA", side:"A", text:"相手の様子を見るより、自分から行く方が早いと思う。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_17", axis:"OA", side:"O", text:"人間観察が好きだと思うことがある。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_18", axis:"OA", side:"A", text:"仕掛ける側になると楽しいことがある。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_19", axis:"OA", side:"O", text:"結果よりも『どうなるか』を見ている時間が好きだ。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_20", axis:"OA", side:"A", text:"結果を出すために自分から動くのが苦ではない。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_21", axis:"OA", side:"O", text:"結論を急ぐより観察したいと思うことがある。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_22", axis:"OA", side:"A", text:"待つより動いた方が気が楽だ。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_23", axis:"OA", side:"O", text:"まず見て、あとで参加するタイプだ。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_24", axis:"OA", side:"A", text:"まず参加して、あとで考えるタイプだ。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_25", axis:"OA", side:"O", text:"人の会話のテンポや間を見てしまうことがある。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_26", axis:"OA", side:"A", text:"テンポが悪いと、自分から話を動かしたくなる。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_27", axis:"OA", side:"O", text:"行動する前に『今じゃない』と判断することがある。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_28", axis:"OA", side:"A", text:"『今だ』と思ったらすぐ動くことがある。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_29", axis:"OA", side:"O", text:"場の観察だけで満足できることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_30", axis:"OA", side:"A", text:"自分が何もしていないと物足りなく感じることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_31", axis:"OA", side:"O", text:"誰かの反応や変化を見抜くのが得意な方だ。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_32", axis:"OA", side:"A", text:"相手を動かすために何か仕掛けることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_33", axis:"OA", side:"O", text:"自分から前に出るより、面白いものを見る方が好きだ。", category:"normal", weight:1.0, fixed:false },
  { id:"OA_34", axis:"OA", side:"A", text:"見ているだけではなく、自分も場を動かしたい。", category:"normal", weight:1.0, fixed:false },

  { id:"OA_35", axis:"OA", side:"O", text:"人の反応を見るだけで結構楽しいと思うことがある。", category:"neta", weight:0.9, fixed:false },
  { id:"OA_36", axis:"OA", side:"A", text:"相手の反応を見たくて、あえて何かしてしまうことがある。", category:"neta", weight:0.9, fixed:false },
  { id:"OA_37", axis:"OA", side:"O", text:"修羅場を『止める』より『観察する』気持ちになることがある。", category:"neta", weight:0.9, fixed:false },
  { id:"OA_38", axis:"OA", side:"A", text:"面白くなりそうだと、自分から空気をかき回すことがある。", category:"neta", weight:0.9, fixed:false },
  { id:"OA_39", axis:"OA", side:"O", text:"人のクセや反応パターンを見つけるのが得意だと思う。", category:"neta", weight:0.9, fixed:false },
  { id:"OA_40", axis:"OA", side:"A", text:"ちょっとした一言で場の空気を変えたくなることがある。", category:"neta", weight:0.9, fixed:false },

  // =========================
  // TP 40問
  // =========================
  { id:"TP_01", axis:"TP", side:"T", text:"嫌なことでも必要なら我慢できる方だ。", category:"core", weight:1.5, fixed:false },
  { id:"TP_02", axis:"TP", side:"P", text:"楽しいことは我慢せず楽しみたいと思う。", category:"core", weight:1.5, fixed:false },
  { id:"TP_03", axis:"TP", side:"T", text:"長く続く努力を苦に感じないことがある。", category:"core", weight:1.5, fixed:false },
  { id:"TP_04", axis:"TP", side:"P", text:"強い刺激や面白いことを求めることがある。", category:"core", weight:1.5, fixed:false },
  { id:"TP_05", axis:"TP", side:"T", text:"多少つらくてもやり抜こうとする。", category:"core", weight:1.5, fixed:false },
  { id:"TP_06", axis:"TP", side:"P", text:"面白そうなことにはすぐ飛びつく。", category:"core", weight:1.5, fixed:false },
  { id:"TP_07", axis:"TP", side:"T", text:"困難を乗り越えることに意味を感じる。", category:"core", weight:1.5, fixed:false },
  { id:"TP_08", axis:"TP", side:"P", text:"刺激がないと退屈に感じることがある。", category:"core", weight:1.5, fixed:false },

  { id:"TP_09", axis:"TP", side:"T", text:"多少つらくても、あとで達成感があればいいと思える。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_10", axis:"TP", side:"P", text:"退屈より少し危険でも面白い方を選びたくなることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_11", axis:"TP", side:"T", text:"我慢強いと言われることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_12", axis:"TP", side:"P", text:"楽しいことを優先したい気持ちが強い。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_13", axis:"TP", side:"T", text:"少し苦しくても『まだいける』と思うことがある。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_14", axis:"TP", side:"P", text:"気持ちよさや楽しさを追い求めたくなることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_15", axis:"TP", side:"T", text:"面倒でも最後までやり切る方だ。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_16", axis:"TP", side:"P", text:"ワクワクすることがあると止められないことがある。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_17", axis:"TP", side:"T", text:"多少の苦しさを前提にした挑戦も嫌いではない。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_18", axis:"TP", side:"P", text:"強い体験や濃い刺激に惹かれることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_19", axis:"TP", side:"T", text:"地味でも積み上げることに意味を感じる。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_20", axis:"TP", side:"P", text:"平凡より『面白さ』を優先したいと思うことがある。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_21", axis:"TP", side:"T", text:"苦しい途中を含めて『挑戦』だと思える。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_22", axis:"TP", side:"P", text:"楽しいことのためなら、多少の後悔は気にしないことがある。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_23", axis:"TP", side:"T", text:"苦労した分だけ価値があると思いやすい。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_24", axis:"TP", side:"P", text:"気持ちよさを追いかける方が人生らしいと思う。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_25", axis:"TP", side:"T", text:"苦痛や面倒を耐えること自体に慣れている方だ。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_26", axis:"TP", side:"P", text:"新しい刺激を見つけると試したくなる。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_27", axis:"TP", side:"T", text:"我慢した先にある達成感が好きだ。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_28", axis:"TP", side:"P", text:"面白さのためなら少し危険でも行きたくなる。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_29", axis:"TP", side:"T", text:"多少不快でも必要なら受け入れられる。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_30", axis:"TP", side:"P", text:"心地よさや快感に正直な方だと思う。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_31", axis:"TP", side:"T", text:"耐えることに変な誇りを感じることがある。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_32", axis:"TP", side:"P", text:"刺激を追っているときの自分が好きだと思うことがある。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_33", axis:"TP", side:"T", text:"ギリギリでも踏ん張れる自信がある。", category:"normal", weight:1.0, fixed:false },
  { id:"TP_34", axis:"TP", side:"P", text:"退屈より刺激的な混乱の方がマシだと思うことがある。", category:"normal", weight:1.0, fixed:false },

  { id:"TP_35", axis:"TP", side:"T", text:"少し恥ずかしいことでも我慢すればいけると思うことがある。", category:"neta", weight:0.9, fixed:false },
  { id:"TP_36", axis:"TP", side:"P", text:"ちょっと危ないくらいの刺激に惹かれることがある。", category:"neta", weight:0.9, fixed:false },
  { id:"TP_37", axis:"TP", side:"T", text:"恥ずかしい状況を耐えた後の達成感が嫌いではない。", category:"neta", weight:0.9, fixed:false },
  { id:"TP_38", axis:"TP", side:"P", text:"『やりすぎかも』と思うくらいがちょうどいいと感じることがある。", category:"neta", weight:0.9, fixed:false },
  { id:"TP_39", axis:"TP", side:"T", text:"つらい状況ほど燃えることがある。", category:"neta", weight:0.9, fixed:false },
  { id:"TP_40", axis:"TP", side:"P", text:"刺激が強いほど面白いと思ってしまうことがある。", category:"neta", weight:0.9, fixed:false }
];

export function getFixedQuestions() {
  return QUESTIONS.filter(q => q.fixed);
}

export function getPoolQuestions() {
  return QUESTIONS.filter(q => !q.fixed);
}
